data:
  name: VisA
  data_dir: /home/anywhere3090l/Desktop/henry/jjmvtec/VisA_dataset
  category: pipe_fryum
  image_size: 256
  batch_size: 8
  DA_batch_size: 8
  test_batch_size: 8
  mask: True
  input_channel: 3

model:
  DDADS: False
  checkpoint_dir: /home/anywhere3090l/Desktop/henry/jjmvtec/checkpoints/VisA
  checkpoint_name: weights
  exp_name: default
  feature_extractor: wide_resnet101_2
  learning_rate: 1e-4
  weight_decay: 0.001
  epochs: 1
  load_chp: 1000
  DA_epochs: 1
  v1: 1
  v2: 1
  w: 6
  w_DA: 0
  DLlambda: 0.05
  trajectory_steps: 1000
  test_trajectoy_steps: 250
  test_trajectoy_steps_DA: 250
  skip: 25
  skip_DA: 25
  eta: 1
  beta_start: 0.0001
  beta_end: 0.02
  device: 'cuda'
  save_model: True
  num_workers: 2
  seed: 42

metrics:
  image_level_AUROC: True  # 或者 False，根据您的需要
  pixel_level_AUROC: True  # 添加这一行
  auroc: True
  pro: True
  misclassifications: False
  visualisation: False

#  python main.py --train Truepython main.py --domain_adaptation Truepython main.py --eval True